spring:
  cloud:
    consul:
      config:
        format: yaml
  config:
    import: consul://
  application:
    name: discount-grpc
#  jpa:
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#  grpc:
#    server:
#      port: 9090
#      enabled: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/discount
#    password: admin1234
#    username: admin
server:
  port: 9090
